// <auto-generated />
using System;
using ApiYoutube.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiYoutube.Migrations
{
    [DbContext(typeof(ApiYoutubeContext))]
    [Migration("20200211010029_Inictial")]
    partial class Inictial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiYoutube.Models.Entity.Canal", b =>
                {
                    b.Property<int>("IdCanal")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescricaoCanal")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("NomeCanal")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("IdCanal");

                    b.ToTable("Canal");
                });

            modelBuilder.Entity("ApiYoutube.Models.Entity.CanalItem", b =>
                {
                    b.Property<int>("IdCanalItem")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComentarioCanalItem")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int?>("IdCanal");

                    b.Property<string>("NomeCanalItem")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.HasKey("IdCanalItem");

                    b.HasIndex("IdCanal");

                    b.ToTable("CanalItem");
                });

            modelBuilder.Entity("ApiYoutube.Models.Entity.CanalItem", b =>
                {
                    b.HasOne("ApiYoutube.Models.Entity.Canal", "Canal")
                        .WithMany()
                        .HasForeignKey("IdCanal");
                });
#pragma warning restore 612, 618
        }
    }
}
